apiVersion: v1
kind: Service
metadata:
  name: nolalhost-svc
  labels:
    app: django-demo-webapp

spec: 
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: django-demo-webapp
  type: ClusterIP
